language: php
sudo: required
dist: trusty
group: edge

php:
    - 7.0
    - 7.1
    - nightly
    - hhvm

matrix:
    allow_failures:
        - php: nightly
        - php: hhvm

install: composer install
